server:
  port: 9999
  servlet:
    context-path: /bookstore
spring:
  application:
    name: bookStore
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis-plus?characterEncoding=UTF-8
    username: root
    password: 123456
logging:
  level:
    root: info
    com:
      duyou:
        dao: debug